import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import { migrate } from '../scripts/migrate.js';
import { signSession } from '../netlify/lib/auth.js';
import { price } from '../netlify/lib/admin-validation.js';
import { createAdminCategoriesHandler } from '../netlify/functions/admin-categories.js';
import { createCategoriesReorderHandler } from '../netlify/functions/admin-categories-reorder.js';
import { createAdminProductsHandler } from '../netlify/functions/admin-products.js';
import { createAdminProductHandler } from '../netlify/functions/admin-product.js';
import { createProductsReorderHandler } from '../netlify/functions/admin-products-reorder.js';
import { createAdminVariantsHandler } from '../netlify/functions/admin-variants.js';
import { createVariantsReorderHandler } from '../netlify/functions/admin-variants-reorder.js';
import { createPublicCategoryHandler } from '../netlify/functions/public-category.js';
import { createPublicProductHandler } from '../netlify/functions/public-product.js';

const silent=()=>{}; const env={NODE_ENV:'development',AUTH_SECRET:randomBytes(48).toString('hex')};
const adapter=db=>({query:async(sql,params)=>params?db.query(sql,params):(await db.exec(sql)).at(-1)});
const body=(method,data,token,queryStringParameters={})=>({httpMethod:method,headers:{'content-type':'application/json',origin:'http://localhost',host:'localhost',...(token?{cookie:`menu_session=${token}`}:{})},body:JSON.stringify(data),queryStringParameters});
const get=(token,queryStringParameters={})=>({httpMethod:'GET',headers:token?{cookie:`menu_session=${token}`}:{},queryStringParameters});
const data=response=>JSON.parse(response.body);

test('FASE 6: migración, validación decimal y visibilidad pública',async t=>{
 const db=new PGlite();try{const client=adapter(db);assert.deepEqual(await migrate(client,undefined,silent),['001_initial_schema.sql','002_unique_user_email_case_insensitive.sql','003_add_products_active.sql','004_business_branding_and_media.sql','005_promotion_carousel_cover.sql','006_login_rate_limits.sql']);assert.deepEqual(await migrate(client,undefined,silent),[]);
  assert.equal((await db.query("SELECT column_default,is_nullable FROM information_schema.columns WHERE table_name='products' AND column_name='active'")).rows[0].is_nullable,'NO');
  for(const value of ['0','10','10.5','10.50','9999999999.99'])assert.ok(price(value)); for(const value of ['-1','NaN','Infinity','1e10','abc','12.345',10])assert.equal(price(value),undefined);
  await db.exec("INSERT INTO businesses(id,name,slug) OVERRIDING SYSTEM VALUE VALUES(1,'A','a'); INSERT INTO categories(id,business_id,name) OVERRIDING SYSTEM VALUE VALUES(1,1,'Cat'); INSERT INTO products(id,business_id,category_id,name,price,active,available) OVERRIDING SYSTEM VALUE VALUES(1,1,1,'Visible',1,true,true),(2,1,1,'Agotado',2,true,false),(3,1,1,'Oculto',3,false,true),(4,1,1,'Oculto agotado',4,false,false)");
  const run=async(sql,p)=>(await db.query(sql,p)).rows; const category=createPublicCategoryHandler(run,silent); const product=createPublicProductHandler(run,silent);
  const cat=data(await category({httpMethod:'GET',queryStringParameters:{slug:'a',category_id:'1'}}));assert.deepEqual(cat.products.map(p=>[p.name,p.available]),[['Visible',true],['Agotado',false]]);
  assert.equal((await product({httpMethod:'GET',queryStringParameters:{slug:'a',category_id:'1',product_id:'2'}})).statusCode,200);assert.equal((await product({httpMethod:'GET',queryStringParameters:{slug:'a',category_id:'1',product_id:'3'}})).statusCode,404);
 }finally{await db.close()}
});

test('FASE 6: categorías, productos y variantes aislados por empresa',async t=>{
 const db=new PGlite();try{await migrate(adapter(db),undefined,silent);await db.exec("INSERT INTO businesses(id,name,slug) OVERRIDING SYSTEM VALUE VALUES(1,'A','a'),(2,'B','b'); INSERT INTO categories(id,business_id,name,sort_order,active) OVERRIDING SYSTEM VALUE VALUES(1,1,'Uno',1,true),(2,1,'Dos',2,false),(9,2,'Ajena',1,true); INSERT INTO products(id,business_id,category_id,name,price,sort_order,active,available,featured) OVERRIDING SYSTEM VALUE VALUES(1,1,1,'P1',10.10,1,true,true,false),(2,1,1,'P2',20,2,false,false,true),(9,2,9,'Ajeno',99,1,true,true,false); INSERT INTO users(id,business_id,name,email,password_hash,role) OVERRIDING SYSTEM VALUE VALUES(1,1,'Owner','a@a.test','hash','OWNER'),(2,2,'Owner B','b@b.test','hash','OWNER'),(3,1,'Staff','s@a.test','hash','STAFF'); SELECT setval(pg_get_serial_sequence('categories','id'),9); SELECT setval(pg_get_serial_sequence('products','id'),9); SELECT setval(pg_get_serial_sequence('product_variants','id'),1,false)");
  const run=async(sql,p)=>(await db.query(sql,p)).rows;const token=await signSession({id:'1',business_id:'1',role:'OWNER'},env);const staff=await signSession({id:'3',business_id:'1',role:'STAFF'},env);
  const categories=createAdminCategoriesHandler(run,env,silent), reorderCategories=createCategoriesReorderHandler(run,env,silent), products=createAdminProductsHandler(run,env,silent), detail=createAdminProductHandler(run,env,silent), reorderProducts=createProductsReorderHandler(run,env,silent), variants=createAdminVariantsHandler(run,env,silent), reorderVariants=createVariantsReorderHandler(run,env,silent);
  await t.test('auth, listado y categorías activas/inactivas',async()=>{assert.equal((await categories(get())).statusCode,401);assert.equal((await categories(get(staff))).statusCode,403);const list=data(await categories(get(token))).categories;assert.deepEqual(list.map(x=>[x.name,x.active]),[['Uno',true],['Dos',false]]);});
  let categoryId;await t.test('crear, validar, editar y rechazar empresa ajena/mass assignment',async()=>{assert.equal((await categories(body('POST',{name:''},token))).statusCode,400);assert.equal((await categories(body('POST',{name:'X',business_id:'2'},token))).statusCode,400);const created=await categories(body('POST',{name:' Tres ',active:true},token));assert.equal(created.statusCode,201);categoryId=data(created).category.id;assert.equal(data(created).category.sort_order,3);const edited=await categories(body('PATCH',{name:'Tres editada',active:false},token,{category_id:categoryId}));assert.equal(data(edited).category.active,false);assert.equal((await categories(body('PATCH',{name:'Hack'},token,{category_id:'9'}))).statusCode,404);});
  await t.test('reordenamiento completo persiste y rechaza IDs ajenos',async()=>{assert.equal((await reorderCategories(body('POST',{category_ids:['9','1','2',categoryId]},token))).statusCode,400);assert.equal((await reorderCategories(body('POST',{category_ids:[categoryId,'2','1']},token))).statusCode,200);assert.deepEqual((await db.query('SELECT id::text id FROM categories WHERE business_id=1 ORDER BY sort_order')).rows.map(x=>x.id),[categoryId,'2','1']);});
  let productId;await t.test('productos: listar todo, crear exacto y validar categoría/precio/nombre',async()=>{const list=data(await products(get(token))).products;assert.deepEqual(list.map(x=>[x.name,x.active,x.available]),[['P1',true,true],['P2',false,false]]);assert.ok(list.every(x=>!('business_id'in x)));for(const bad of [{category_id:'9',name:'Nuevo',price:'1.00'},{category_id:'1',name:'',price:'1.00'},{category_id:'1',name:'Nuevo',price:'12.345'}])assert.notEqual((await products(body('POST',bad,token))).statusCode,201);const created=await products(body('POST',{category_id:'1',name:'Nuevo',description:'texto',price:'75.5',active:true,available:true,featured:false},token));assert.equal(created.statusCode,201);productId=data(created).product.id;assert.equal(data(created).product.price,'75.50');assert.equal(data(created).product.image_url,null);});
  await t.test('editar estados, precio, categoría y proteger producto ajeno',async()=>{const updated=await products(body('PATCH',{category_id:'2',price:'80.25',available:false,featured:true,active:false},token,{product_id:productId}));const p=data(updated).product;assert.deepEqual([p.category_id,p.price,p.available,p.featured,p.active],['2','80.25',false,true,false]);assert.equal((await products(body('PATCH',{name:'Hack'},token,{product_id:'9'}))).statusCode,404);assert.equal((await detail(get(token,{product_id:'9'}))).statusCode,404);assert.equal(data(await detail(get(token,{product_id:productId}))).variants.length,0);});
  await t.test('ordenar productos solo dentro de categoría',async()=>{assert.equal((await reorderProducts(body('POST',{category_id:'1',product_ids:['9','1','2']},token))).statusCode,400);assert.equal((await reorderProducts(body('POST',{category_id:'1',product_ids:['1','2']},token))).statusCode,200);});
  let v1,v2;await t.test('crear variantes, validar producto/precio y editar',async()=>{assert.equal((await variants(body('POST',{product_id:'9',name:'X',price:'1'},token))).statusCode,404);assert.equal((await variants(body('POST',{product_id:productId,name:'X',price:'1.234'},token))).statusCode,400);let r=await variants(body('POST',{product_id:productId,name:'Chico',price:'30'},token));v1=data(r).variant.id;assert.equal(data(r).variant.price,'30.00');r=await variants(body('POST',{product_id:productId,name:'Grande',price:'50.5'},token));v2=data(r).variant.id;const edited=data(await variants(body('PATCH',{name:'Chica',price:'31.25',active:false},token,{variant_id:v1}))).variant;assert.deepEqual([edited.name,edited.price,edited.active],['Chica','31.25',false]);assert.equal((await variants(body('PATCH',{name:'Hack'},token,{variant_id:'999'}))).statusCode,404);});
  await t.test('ordenar variantes y detalle admin incluye inactivas',async()=>{assert.equal((await reorderVariants(body('POST',{product_id:productId,variant_ids:['999',v1,v2]},token))).statusCode,400);assert.equal((await reorderVariants(body('POST',{product_id:productId,variant_ids:[v2,v1]},token))).statusCode,200);const d=data(await detail(get(token,{product_id:productId})));assert.deepEqual(d.variants.map(x=>[x.id,x.active]),[[v2,true],[v1,false]]);});
 }finally{await db.close()}
});
