import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import AdminNav from '../components/admin/AdminNav.jsx';
import { useAuth } from '../components/admin/AuthProvider.jsx';
import { createAdminCategory, getAdminCategories, updateAdminCategory } from '../services/api.js';
import MediaUploader from '../components/admin/MediaUploader.jsx';
import { themeStyle } from '../utils/theme.js';
export default function AdminCategoryFormPage(){
 const {categoryId}=useParams(); const editing=Boolean(categoryId); const auth=useAuth(); const navigate=useNavigate(); const lock=useRef(false); const [loading,setLoading]=useState(editing); const [name,setName]=useState(''); const [image,setImage]=useState(null); const [active,setActive]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{document.title=`${editing?'Editar':'Nueva'} categoría | Menú digital`; if(editing)getAdminCategories().then(d=>{const item=d.categories.find(c=>c.id===categoryId);if(!item)throw Object.assign(new Error(),{status:404});setName(item.name);setImage(item.image_url);setActive(item.active);setLoading(false)}).catch(e=>{if([401,403].includes(e.status))auth.clearSession();else setError(e.status===404?'No encontramos esta categoría.':'No pudimos cargar la categoría.');setLoading(false)});return()=>{document.title='Menú digital'}},[categoryId]);
 const submit=async e=>{e.preventDefault();if(lock.current)return;if(!name.trim()){setError('Escribe un nombre para la categoría.');return}lock.current=true;setBusy(true);setError('');try{if(editing)await updateAdminCategory(categoryId,{name,active});else await createAdminCategory({name,active});navigate('/admin/menu?tab=categories&saved=1')}catch(err){if([401,403].includes(err.status))auth.clearSession();else setError('No pudimos guardar la categoría. Revisa los datos.')}finally{lock.current=false;setBusy(false)}};
 return <main className="admin-shell admin-dashboard" style={themeStyle(auth.business.theme_color)}><AdminNav/><section className="admin-form-page"><Link className="admin-back" to="/admin/menu?tab=categories">← Volver a Menú</Link><h1>{editing?'Editar categoría':'Nueva categoría'}</h1>{loading?<div className="admin-skeleton"/>:<><form onSubmit={submit}><label>Nombre<input required maxLength="120" value={name} onChange={e=>setName(e.target.value)}/></label><label className="admin-toggle"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><span>Visible en el menú</span></label>{error&&<p className="admin-error" role="alert">{error}</p>}<button className="admin-primary" disabled={busy}>{busy?'Guardando…':'Guardar categoría'}</button></form>{editing&&<MediaUploader label="Imagen de categoría" target="category" entityId={categoryId} value={image} onChange={setImage} onUnauthorized={auth.clearSession}/>}</>}</section></main>
}
