import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import AdminNav from '../components/admin/AdminNav.jsx';
import { useAuth } from '../components/admin/AuthProvider.jsx';
import { createAdminProduct, createAdminVariant, getAdminCategories, getAdminProduct, reorderAdminVariants, updateAdminProduct, updateAdminVariant } from '../services/api.js';
import { formatPrice } from '../utils/products.js';
import MediaUploader from '../components/admin/MediaUploader.jsx';

function VariantRow({ item, onSave, onMove, first, last }) {
 const [editing,setEditing]=useState(false); const [name,setName]=useState(item.name); const [price,setPrice]=useState(item.price); const [active,setActive]=useState(item.active); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(item.id,{name,price,active});setEditing(false)}catch{setError('Revisa nombre y precio.')}finally{setBusy(false)}};
 return <li className="admin-variant">{editing?<form onSubmit={save}><label>Nombre<input required maxLength="120" value={name} onChange={e=>setName(e.target.value)}/></label><label>Precio<input required inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="admin-toggle"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><span>Mostrar presentación</span></label>{error&&<p className="admin-field-error">{error}</p>}<div className="admin-form-actions"><button className="admin-primary" disabled={busy}>{busy?'Guardando…':'Guardar'}</button><button type="button" className="admin-secondary" onClick={()=>setEditing(false)}>Cancelar</button></div></form>:<><div><strong>{item.name}</strong><span>{formatPrice(item.price)} · {item.active?'Visible':'Oculta'}</span></div><div className="admin-item-actions"><button aria-label={`Subir ${item.name}`} disabled={first} onClick={()=>onMove(item,-1)}>↑</button><button aria-label={`Bajar ${item.name}`} disabled={last} onClick={()=>onMove(item,1)}>↓</button><button onClick={()=>setEditing(true)}>Editar</button></div></>}</li>;
}

export default function AdminProductFormPage(){
 const {productId}=useParams(); const editing=Boolean(productId); const auth=useAuth(); const navigate=useNavigate(); const lock=useRef(false);
 const [loading,setLoading]=useState(true); const [categories,setCategories]=useState([]); const [variants,setVariants]=useState([]); const [image,setImage]=useState(null); const [form,setForm]=useState({category_id:'',name:'',description:'',price:'',active:true,available:true,featured:false}); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState(''); const [newVariant,setNewVariant]=useState({name:'',price:''}); const [variantBusy,setVariantBusy]=useState(false);
 const change=(key,value)=>setForm(f=>({...f,[key]:value}));
 useEffect(()=>{document.title=`${editing?'Editar':'Nuevo'} producto | Menú digital`; Promise.all([getAdminCategories(),editing?getAdminProduct(productId):Promise.resolve(null)]).then(([c,d])=>{setCategories(c.categories);if(d){setForm({category_id:d.product.category_id,name:d.product.name,description:d.product.description??'',price:d.product.price,active:d.product.active,available:d.product.available,featured:d.product.featured});setImage(d.product.image_url);setVariants(d.variants)}else if(c.categories.length)setForm(f=>({...f,category_id:c.categories[0].id}));setLoading(false)}).catch(e=>{if([401,403].includes(e.status))auth.clearSession();else setError(e.status===404?'No encontramos este producto.':'No pudimos cargar el producto.');setLoading(false)});return()=>{document.title='Menú digital'}},[productId]);
 const submit=async e=>{e.preventDefault();if(lock.current)return;setError('');if(!form.name.trim()){setError('Escribe un nombre para el producto.');return}if(!/^(?:0|[1-9][0-9]{0,9})(?:\.[0-9]{1,2})?$/.test(form.price)){setError('Ingresa un precio válido.');return}lock.current=true;setBusy(true);try{const body={...form,description:form.description||null};if(editing){await updateAdminProduct(productId,body);setSaved('Producto actualizado.')}else{const data=await createAdminProduct(body);navigate(`/admin/menu/productos/${data.product.id}/editar?created=1`,{replace:true})}}catch(err){if([401,403].includes(err.status))auth.clearSession();else setError(err.code==='CATEGORY_NOT_FOUND'?'Selecciona una categoría válida.':'No pudimos guardar el producto. Revisa los datos.')}finally{lock.current=false;setBusy(false)}};
 const saveVariant=async(id,body)=>{const data=await updateAdminVariant(id,body);setVariants(v=>v.map(x=>x.id===id?data.variant:x));setSaved('Presentación actualizada.')};
 const addVariant=async e=>{e.preventDefault();setError('');setVariantBusy(true);try{const data=await createAdminVariant({product_id:productId,...newVariant});setVariants(v=>[...v,data.variant]);setNewVariant({name:'',price:''});setSaved('Presentación agregada.')}catch{setError('No pudimos agregar la presentación. Revisa nombre y precio.')}finally{setVariantBusy(false)}};
 const moveVariant=async(item,delta)=>{const next=[...variants];const index=next.findIndex(v=>v.id===item.id);const other=index+delta;if(other<0||other>=next.length)return;[next[index],next[other]]=[next[other],next[index]];try{await reorderAdminVariants(productId,next.map(v=>v.id));setVariants(next)}catch{setError('No pudimos cambiar el orden de las presentaciones.')}};
 return <main className="admin-shell admin-dashboard"><AdminNav/><section className="admin-form-page admin-product-form"><Link className="admin-back" to="/admin/menu?tab=products">← Volver a Menú</Link><h1>{editing?'Editar producto':'Nuevo producto'}</h1>{saved&&<p className="admin-success" role="status">{saved}</p>}{loading?<div className="admin-skeleton"/>:!categories.length?<div className="admin-empty"><p>Primero crea una categoría.</p><Link to="/admin/menu/categorias/nueva">Crear categoría</Link></div>:<form onSubmit={submit}><label>Categoría<select required value={form.category_id} onChange={e=>change('category_id',e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}{c.active?'':' (oculta)'}</option>)}</select></label><label>Nombre<input required maxLength="160" value={form.name} onChange={e=>change('name',e.target.value)}/></label><label>Descripción <span>Opcional</span><textarea maxLength="1000" rows="5" value={form.description} onChange={e=>change('description',e.target.value)}/></label><label>Precio base<input required inputMode="decimal" placeholder="75.00" value={form.price} onChange={e=>change('price',e.target.value)}/></label><fieldset className="admin-toggle-group"><legend>Estado del producto</legend>{[['active','Visible en el menú'],['available','Disponible'],['featured','Recomendado']].map(([key,label])=><label className="admin-toggle" key={key}><input type="checkbox" checked={form[key]} onChange={e=>change(key,e.target.checked)}/><span>{label}</span></label>)}</fieldset>{error&&<p className="admin-error" role="alert">{error}</p>}<button className="admin-primary" disabled={busy}>{busy?'Guardando…':'Guardar producto'}</button></form>}
 {editing&&!loading&&<><MediaUploader label="Imagen de producto" target="product" entityId={productId} value={image} onChange={setImage} onUnauthorized={auth.clearSession}/><section className="admin-variants-section"><h2>Presentaciones</h2>{!variants.length?<p className="admin-muted">Este producto no tiene presentaciones.</p>:<ul className="admin-variants">{variants.map((v,i)=><VariantRow key={v.id} item={v} first={!i} last={i===variants.length-1} onSave={saveVariant} onMove={moveVariant}/>)}</ul>}<form className="admin-add-variant" onSubmit={addVariant}><h3>Agregar presentación</h3><label>Nombre<input required maxLength="120" placeholder="Ej. Grande" value={newVariant.name} onChange={e=>setNewVariant(v=>({...v,name:e.target.value}))}/></label><label>Precio<input required inputMode="decimal" placeholder="50.00" value={newVariant.price} onChange={e=>setNewVariant(v=>({...v,price:e.target.value}))}/></label><button className="admin-secondary" disabled={variantBusy}>{variantBusy?'Agregando…':'+ Agregar presentación'}</button></form></section></>}
 </section></main>
}
