import { useEffect, useState } from 'react';
import AdminNav from '../components/admin/AdminNav.jsx';
import MediaUploader from '../components/admin/MediaUploader.jsx';
import { useAuth } from '../components/admin/AuthProvider.jsx';
import { getAdminBusiness, updateAdminBusiness } from '../services/api.js';
import { themeColor, themeStyle } from '../utils/theme.js';
export default function AdminBusinessPage(){
 const auth=useAuth();const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState('');const [form,setForm]=useState(null);
 useEffect(()=>{document.title='Mi negocio | Menú digital';getAdminBusiness().then(d=>{setForm(d.business);setLoading(false)}).catch(e=>{if([401,403].includes(e.status))auth.clearSession();else setError('No pudimos cargar tu negocio.');setLoading(false)});return()=>{document.title='Menú digital'}},[]);
 const change=(key,value)=>setForm(f=>({...f,[key]:value}));const submit=async e=>{e.preventDefault();setBusy(true);setError('');setSaved('');try{const d=await updateAdminBusiness({name:form.name,description:form.description||null,address:form.address||null,phone:form.phone||null,theme_color:form.theme_color||null});setForm(d.business);setSaved('Información actualizada.')}catch(err){if([401,403].includes(err.status))auth.clearSession();else setError('No pudimos guardar los cambios. Revisa los datos.')}finally{setBusy(false)}};
 return <main className="admin-shell admin-dashboard" style={themeStyle(form?.theme_color??auth.business.theme_color)}><AdminNav/><section className="admin-form-page admin-business-page"><p className="admin-eyebrow">Configuración</p><h1>Mi negocio</h1>{saved&&<p className="admin-success" role="status">{saved}</p>}{error&&<p className="admin-error" role="alert">{error}</p>}{loading?<div className="admin-skeleton"/>:form&&<><div className="media-grid"><MediaUploader label="Logo" target="business_logo" value={form.logo_url} onChange={v=>change('logo_url',v)} onUnauthorized={auth.clearSession}/><MediaUploader label="Portada" target="business_cover" value={form.cover_url} onChange={v=>change('cover_url',v)} onUnauthorized={auth.clearSession}/></div><form onSubmit={submit}><label>Nombre<input required maxLength="160" value={form.name} onChange={e=>change('name',e.target.value)}/></label><label>Slug público<input disabled value={form.slug}/><span>El slug no se puede modificar.</span></label><label>Descripción<textarea rows="5" maxLength="1000" value={form.description??''} onChange={e=>change('description',e.target.value)}/></label><label>Dirección<input maxLength="300" value={form.address??''} onChange={e=>change('address',e.target.value)}/></label><label>Teléfono<input maxLength="40" value={form.phone??''} onChange={e=>change('phone',e.target.value)}/></label><label>Color de marca<div className="theme-picker"><input type="color" value={themeColor(form.theme_color)} onChange={e=>change('theme_color',e.target.value.toUpperCase())}/><input pattern="#[0-9A-Fa-f]{6}" value={form.theme_color??''} placeholder="#9250D8" onChange={e=>change('theme_color',e.target.value)}/></div></label><button className="admin-primary" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></form></>}</section></main>
}
