import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import AdminNav from '../components/admin/AdminNav.jsx';
import { useAuth } from '../components/admin/AuthProvider.jsx';
import { themeStyle } from '../utils/theme.js';
import { formatPrice } from '../utils/products.js';
import { getAdminCategories, getAdminProducts, reorderAdminCategories, reorderAdminProducts, updateAdminProduct } from '../services/api.js';

export default function AdminMenuPage() {
  const auth = useAuth(); const [params, setParams] = useSearchParams(); const tab = params.get('tab') === 'products' ? 'products' : 'categories';
  const [state, setState] = useState({ status: 'loading', categories: [], products: [] }); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('all'); const [filter, setFilter] = useState('all');
  const load = async () => { setState(s => ({ ...s, status: 'loading' })); setError(''); try { const [c, p] = await Promise.all([getAdminCategories(), getAdminProducts()]); setState({ status: 'success', categories: c.categories, products: p.products }); } catch (e) { if ([401,403].includes(e.status)) auth.clearSession(); else setState(s => ({ ...s, status: 'error' })); } };
  useEffect(() => { document.title = `Menú | ${auth.business.name}`; load(); return () => { document.title = 'Menú digital'; }; }, []);
  const moveCategory = async (index, delta) => { const next = [...state.categories]; const other = index + delta; if (other < 0 || other >= next.length) return; [next[index], next[other]] = [next[other], next[index]]; try { await reorderAdminCategories(next.map(x => x.id)); setState(s => ({ ...s, categories: next })); } catch { setError('No pudimos cambiar el orden.'); } };
  const moveProduct = async (product, delta) => { const group = state.products.filter(p => p.category_id === product.category_id); const index = group.findIndex(p => p.id === product.id); const other = index + delta; if (other < 0 || other >= group.length) return; [group[index], group[other]] = [group[other], group[index]]; try { await reorderAdminProducts(product.category_id, group.map(p => p.id)); const rank = new Map(group.map((p,i) => [p.id,i])); setState(s => ({ ...s, products: [...s.products].sort((a,b) => a.category_id === product.category_id && b.category_id === product.category_id ? rank.get(a.id)-rank.get(b.id) : 0) })); } catch { setError('No pudimos cambiar el orden.'); } };
  const toggleAvailable = async product => { const value = !product.available; try { await updateAdminProduct(product.id, { available: value }); setState(s => ({ ...s, products: s.products.map(p => p.id === product.id ? { ...p, available: value } : p) })); } catch (e) { if ([401,403].includes(e.status)) auth.clearSession(); else setError('No pudimos actualizar la disponibilidad.'); } };
  const products = useMemo(() => state.products.filter(p => p.name.toLocaleLowerCase('es').includes(search.trim().toLocaleLowerCase('es')) && (category === 'all' || p.category_id === category) && (filter === 'all' || filter === 'visible' && p.active || filter === 'hidden' && !p.active || filter === 'available' && p.available || filter === 'soldout' && !p.available || filter === 'featured' && p.featured)), [state.products, search, category, filter]);
  return <main className="admin-shell admin-dashboard" style={themeStyle(auth.business.theme_color)}><AdminNav />
    <section className="admin-page-title"><p className="admin-eyebrow">Menú</p><h1>Administra tu menú</h1><p>Administra lo que tus clientes pueden consultar.</p></section>
    {params.get('saved') && <p className="admin-success" role="status">Cambios guardados.</p>}{error && <p className="admin-error" role="alert">{error}</p>}
    <div className="admin-tabs" role="tablist" aria-label="Contenido del menú"><button role="tab" aria-selected={tab==='categories'} onClick={() => setParams({ tab:'categories' })}>Categorías</button><button role="tab" aria-selected={tab==='products'} onClick={() => setParams({ tab:'products' })}>Productos</button></div>
    {state.status === 'loading' && <div className="admin-list" aria-label="Cargando contenido">{[1,2,3].map(x => <div className="admin-skeleton" key={x}/>)}</div>}
    {state.status === 'error' && <div className="admin-error"><p>No pudimos cargar tu menú.</p><button className="admin-secondary" onClick={load}>Reintentar</button></div>}
    {state.status === 'success' && tab === 'categories' && <section className="admin-manage"><div className="admin-section-bar"><div><h2>Categorías</h2><p>{state.categories.length} {state.categories.length===1?'categoría':'categorías'}</p></div><Link className="admin-primary admin-link-button" to="/admin/menu/categorias/nueva">+ Nueva categoría</Link></div>
      {!state.categories.length ? <div className="admin-empty"><p>Aún no tienes categorías.</p><Link to="/admin/menu/categorias/nueva">Crear primera categoría</Link></div> : <ul className="admin-list">{state.categories.map((item,index) => <li className="admin-list-item" key={item.id}><div className="admin-item-main"><h3>{item.name}</h3><span className={`admin-status ${item.active?'is-on':'is-off'}`}>{item.active?'Visible':'Oculta'}</span></div><div className="admin-item-actions"><button aria-label={`Subir ${item.name}`} disabled={!index} onClick={() => moveCategory(index,-1)}>↑ <span>Subir</span></button><button aria-label={`Bajar ${item.name}`} disabled={index===state.categories.length-1} onClick={() => moveCategory(index,1)}>↓ <span>Bajar</span></button><Link to={`/admin/menu/categorias/${item.id}/editar`}>Editar</Link></div></li>)}</ul>}
    </section>}
    {state.status === 'success' && tab === 'products' && <section className="admin-manage"><div className="admin-section-bar"><div><h2>Productos</h2><p>{state.products.length} en total</p></div>{state.categories.length ? <Link className="admin-primary admin-link-button" to="/admin/menu/productos/nuevo">+ Nuevo producto</Link> : null}</div>
      {!state.categories.length ? <div className="admin-empty"><p>Primero crea una categoría.</p><Link to="/admin/menu/categorias/nueva">Crear categoría</Link></div> : <><div className="admin-filters"><label>Buscar productos<input type="search" placeholder="Buscar productos…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Categoría<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas las categorías</option>{state.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Estado<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="visible">Visibles</option><option value="hidden">Ocultos</option><option value="available">Disponibles</option><option value="soldout">Agotados</option><option value="featured">Recomendados</option></select></label></div>
      {!state.products.length ? <div className="admin-empty"><p>Aún no tienes productos.</p><Link to="/admin/menu/productos/nuevo">Crear primer producto</Link></div> : !products.length ? <div className="admin-empty"><p>No encontramos productos con esos filtros.</p></div> : <ul className="admin-list">{products.map(item => { const group=state.products.filter(p=>p.category_id===item.category_id); const index=group.findIndex(p=>p.id===item.id); return <li className="admin-list-item admin-product-item" key={item.id}><div className="admin-item-main"><h3>{item.name}</h3><p>{item.category.name} · {formatPrice(item.price)}</p><div className="admin-statuses"><span>{item.active?'Visible':'Oculto'}</span>{item.featured&&<span>Recomendado</span>}</div></div><div className="admin-item-actions"><button className={item.available?'is-available':'is-soldout'} onClick={()=>toggleAvailable(item)}>{item.available?'Disponible':'Agotado'}</button><button aria-label={`Subir ${item.name}`} disabled={!index} onClick={()=>moveProduct(item,-1)}>↑</button><button aria-label={`Bajar ${item.name}`} disabled={index===group.length-1} onClick={()=>moveProduct(item,1)}>↓</button><Link to={`/admin/menu/productos/${item.id}/editar`}>Editar</Link></div></li>;})}</ul>}</>}
    </section>}
  </main>;
}
